version: '2'
services:
  zabbix-server:
    image: zabbix/zabbix-server-mysql:alpine-latest
    container_name: zabbix-server
    environment:
      - ZBX_HOSTNAME=zabbix-server
      - DB_SERVER_HOST=192.168.255.1
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - ZBX_STARTPOLLERS=5
      - ZBX_STARTPINGERS=2
      - ZBX_STARTDISCOVERERS=2
      - ZBX_STARTDBSYNCERS=4
      - ZBX_DEBUGLEVEL=2
    ports:
      - "10051:10051"
      - "162:162"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /usr/share/snmp/mibs:/var/lib/zabbix/mibs
    networks:
      zbxnet:
        ipv4_address: 192.168.255.2

  zabbix-web:
    build: zabbix-web
    container_name: zabbix-web
    environment:
      - DB_SERVER_HOST=192.168.255.1
      - MYSQL_USER=zabbix
      - MYSQL_PASSWORD=zabbix
      - MYSQL_DATABASE=zabbix
      - PHP_TZ="Asia/Tokyo"
    links:
      - zabbix-server
    ports:
      - "8080:80"
    volumes:
      - /etc/localtime:/etc/localtime:ro
    networks:
      zbxnet:
        ipv4_address: 192.168.255.3

networks:
  zbxnet:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 192.168.255.0/24
